# Generated by Django 6.0.2 on 2026-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('operating_personnel', 'Operating Personnel')], max_length=50),
        ),
    ]
