# Generated by Django 6.0.2 on 2026-02-10 11:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('driver', 'Driver'), ('helper', 'Helper'), ('staff', 'Staff')], max_length=50)),
                ('philhealth_number', models.CharField(max_length=80, unique=True)),
                ('pag_ibig_number', models.CharField(max_length=80, unique=True)),
                ('sss_number', models.CharField(max_length=80, unique=True)),
                ('drivers_license_number', models.CharField(max_length=80, unique=True)),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Philippine mobile number (e.g., 09171234567 or +639171234567).', regex='^(09|\\+639)\\d{9}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
